### ISSUE TITLE
Great Promise!

### ISSUE THREAD

**Issue by NorfolkGreg** [AndInTheClouds/chordreader2#10]
I'm no coder and don't understand how GitHub works but just wanted to ask how I can help improve and promote this project.

Currently using Lyric Pad, but this interface is so much more intuitive, but I'd like to see some tweaks and discuss ideas.

Any chance of emailing gregwebdesigner_gmail (you can guess the rest!).

Hope this follows GitHub guidelines.

**Comment by wtimme** [comment]
Hey @NorfolkGreg,

I'm not the maintainer, but I'd be interested in your ideas and tweaks as well. If you don't mind, how about we use GitHub issues to keep track of these? If you're not familiar or just would like to kick things off, how about we use _this_ GitHub issue as a starting point?

Thanks in advance for your effort! Looking forward to your input.

**Comment by AndInTheClouds** [comment]
Hi @NorfolkGreg, 
thanks for your offering from my side, too. I agree with @wtimme to discuss your thoughts here. Please feel free to share your ideas.
Regards

**Comment by wtimme** [comment]
I am going to close this issue, as there's nothing to do here. Again, if you have any feedback or input, please do not hesitate to open a dedicated issue. Thanks in advance!
