### ISSUE TITLE
Provide a changelog in F-Droid

### ISSUE THREAD

**Issue by nach0** [AndInTheClouds/chordreader2#13]
Could we please get changelogs for the new versions? I find it's good practice to read the changelog of an app before updating it, to know what you're installing.

The app was recently updated to version 2.1.3, but there is no changelog provided on the release page. Is this information maybe shown elsewhere?

**Comment by wtimme** [comment]
Hey @nach0,

Thank you very much for your feedback! You can find the changelog either in the app itself (see "About" in the drawer menu) or [here on GitHub, under "Releases"](https://github.com/AndInTheClouds/chordreader2/releases).

From what I can tell, the changelog could also be integrated into F-Droid. I am going to change the title of this issue accordingly.

**Comment by nach0** [comment]
Hi @wtimme, thank you very much for your answer.

I feel a bit stupid, since I had already checked the GitHub releases page but didn't see the changelogs there. The issue is I use [Octodroid](https://github.com/MedanLinux/octo-droid) on my smartphone and for some reason it doesn't display ChordReader2's changelogs. For other apps, like [Metronome](https://github.com/Kr0oked/Metronome/releases) it works, though. I believe the way the changelogs text is stored on the release page might be responsible for this. 

Having the changelog in F-Droid would be great, thanks. This would save me a couple of taps to check the GitHub releases :)

**Comment by AndInTheClouds** [comment]
Hi @nach0,
the changelog will be an F-Droid with the next release. Regards
