### ISSUE TITLE
Chord name does not related to a key

### ISSUE THREAD

**Issue by ForrestPanda** [AndInTheClouds/chordreader2#14]
I've noticed that the app changes the chords names it finds on a page, but doesn't take into consideration the key

For example [this song](https://www.cifraclub.com.br/miguel-araujo/balada-astral/) C#m and F#m are modified to Dbm and Gbm respectively. However these should be kept as C#m and F#m to follow the notes E F# G# A B C# D# of the E major key.

It would be nice to have the option to not modify the chord names of the page.

As a side note it would be nice to have the option to modify the names of the chords to fit the key of the song, in case they were written not taking this into consideration.

**Comment by AndInTheClouds** [comment]
Hi ForrestPanda,
currently there is an option in the settings to change the "note namings". If you choose "NorthernEuropean" then the #-version of the chord is displayed instead. I hope that solve your issue. 
Regards
