### ISSUE TITLE
Please allow manual change of sharp and flat keys

### ISSUE THREAD

**Issue by muffinmaster1024** [AndInTheClouds/chordreader2#25]
Curently it shows all chords in flat key, even when the original key is shown as sharp.
It is also very confusing while playing.

**Comment by wtimme** [comment]
Hey @muffinmaster1024, thank you very much for your input!

Could you provide us with more information? For example, the following would be helpful:

- the URL to an example page that causes the behaviour
- a concrete chord that allows one to compare the _expected_ behaviour with the _observed_ one

Thank in advance!

**Comment by AndInTheClouds** [comment]
Hi muffinmaster1024,
currently there is an option in the settings to change the "note namings". If you choose "NorthernEuropean" then the #-version of the chord is displayed instead. I hope that solve your issue.
Regards

**Comment by Cornwallis89** [comment]
Hi AndInTheClouds,

Thank you for your time and effort in making a wonderul and useful application.

I'm having the same issue as OP, and while the proposed solution (using Northern European note namings) offers a limited fix, it does not work on all songs, namely any that include A#/Bb or B.  A#/Bb is displayed as B and B as H.

I'm writing to see if there's another potential workaround to this, and/or for a feature request for an additional note naming option to English with sharps to circumvent this issue.

Thanks!

**Comment by AndInTheClouds** [comment]
This is a tricky issue. As far as I understood from musical theory both # and b can live aside which depends from its context, e.g. the key of the song. However, the current technical implementation of that note parsing, naming, transposition etc. does not reflect that at all. Revision of that part is out of my capabilities. So I just added an option for "English with sharps" as dirty hack.
If someone feels encouraged enough to contribute here, feel free to make a pull request ;)
