### ISSUE TITLE
Doesn't recognize unicode sharp and flat characters

### ISSUE THREAD

**Issue by Mrifk** [AndInTheClouds/chordreader2#31]
If I feed this program the following chord symbols:
`B♭ C♯ Bb C#`
and then tell it to transpose a half-step up, I get:
`C♭ Db♯ B D`
Ideally it'd treat ♭ and ♯ the same as b and #. (If you want to get really fancy with it, detect whether a file is using the ASCII or Unicode versions and use those in the output too... but I'd settle for everything being ASCII as long as it picks up on the Unicode symbols.)

This isn't a _huge_ issue since I can just find and replace in any files I have that are formatted like this, but it also seems like an easy fix.

**Comment by tutiluren** [comment]
Not huge, but sounds easy enough to address. Do you have a URL to try with?

**Comment by AndInTheClouds** [comment]
Solved
