### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by HDavo** [AndInTheClouds/chordreader2#39]
First of all, the app it's pretty useful and I want to thank you for all the work done in the app.
I've been working in a spanish translation of the app, my knowledge in Android it's very limited so, for now, this is the only way that I can contribute.

The translation it's almost finished (I have to review some typos) in the strings.xml (es) file and in the about_body file, all the translated strings are displayed correctly in the app but I'm not able to see the content of the about file, I changed the language (french and spanish in the system settings) but the content displayed in the about section it's always the english one. 

![imagen](https://github.com/AndInTheClouds/chordreader2/assets/99563047/064acc89-f87a-4d8f-abe5-a017141833a6)

![imagen](https://github.com/AndInTheClouds/chordreader2/assets/99563047/9683a716-6d09-4846-8cd8-4298639340fe)

I've added the strings "songs" and "setlists" in all the values files (en, de, fr and es) because the text in the button and in the menu was harcoded, if this is a change that I shouldn't have made I'll revert it before the pull request. This change allows a better language localisation IMO.

![imagen](https://github.com/AndInTheClouds/chordreader2/assets/99563047/843cacd7-883a-4ebf-89e9-7e11f3c01d53)

![imagen](https://github.com/AndInTheClouds/chordreader2/assets/99563047/d31f3d17-fc6e-4826-98ca-b542cd49df7b)

As soon as the review it's completed I'll submit the pull request.

I just submitted the pull request, sorry if i did to many commits during the translation process.
#40

**Comment by AndInTheClouds** [comment]
Thanks for contribution. Feel free to hint for or correct any typo / wording errors in future strings ;)
