### ISSUE TITLE
All files access

### ISSUE THREAD

**Issue by aricooperdavis** [AndInTheClouds/chordreader2#4]
Firstly, great app, I love the concept!

At the moment on launch it requests all files access. There's no need for this, it would be fine for it to write chords files to its internal data directory or to an external folder using the [Storage Access Framework](https://developer.android.com/training/data-storage/shared/documents-files).

Maybe not a big deal, but it's a bit of a turn-off for many privacy minded FOSS users I suspect!

Thanks,
Ari

**Comment by AndInTheClouds** [comment]
Thanks for your advice. You are right and I will change that in furture releases. 

Regards hitc
