### ISSUE TITLE
new chord

### ISSUE THREAD

**Issue by cl-22** [AndInTheClouds/chordreader2#41]
How can I add a chord that doesn't exist in Chord2? 
Thanks

**Comment by AndInTheClouds** [comment]
You can tap the chord in text to open the dialog for chord fingering. There you can tap 'Edit' to revise all fingerings shown in the app. 
![grafik](https://github.com/AndInTheClouds/chordreader2/assets/70232673/b9f76faf-4bb8-46be-8db1-af041ae74c2e)



Which chord is missing?
Regards

**Comment by cl-22** [comment]
Thanks for your feedback.
I use the editor from time to time to add new fingerings. But sometimes the chord is missing, for example B7b5.
A very nice application that I use a lot.
Best regards
 Claude


Le 26 février 2024 22:35:42 GMT+01:00, andintheclouds ***@***.***> a écrit :

**Comment by AndInTheClouds** [comment]
Chord database was revised and extended. Should be available now.

**Comment by cl-22** [comment]
Thank you.


Le 16 août 2024 11:08:28 GMT+02:00, andintheclouds ***@***.***> a écrit :
