### ISSUE TITLE
App crashes using Nextcloud path

### ISSUE THREAD

**Issue by bastla** [AndInTheClouds/chordreader2#43]
Hi and first of all: thanks for this project! I'm currently facing an issue syncing the data into Nextcloud:

1. Configure `Settings/Storage location` to a new or existing cloud folder.
2. Create a new song or search for a song and store it.
3. Everything works fine.
4. Close song and try to reopen it.
5. App crashes all the time you want to access any of the songs.

If you change back to a local folder everything is working as expected again.

**Comment by AndInTheClouds** [comment]
Solved in version 2.3.0
