### ISSUE TITLE
[Feature request] Add ability to change search engine (ex : duckduckgo)

### ISSUE THREAD

**Issue by pouek** [AndInTheClouds/chordreader2#48]
Hi,
The app's page on F-Droid states that it uses a non-free service (I suppose startpage).
Couldn't it be fixed by setting the search engine to duckduckgo ?

**Comment by AndInTheClouds** [comment]
Hi,
you can set your favorite search engine in the settings. I'm not sure if it resolves the issue to switch to duckduckgo by default as still in the current implementation the default value is hard coded. I'll try searx.work as default.
