### ISSUE TITLE
New versions can't open 

### ISSUE THREAD

**Issue by wolfhoog** [AndInTheClouds/chordreader2#57]
I am using this app since some years. (Thanks by the way.)
But the new versions always immediate close when they are opened.
(Version 2.2.0 is still working though.)
(I have MIUI based on Android 10. All the other F-Droid app updates are working.)

**Comment by Benko111** [comment]
Same here. Getting instant FC when launching the app, setting permission before opening doesn't help. Pity.

**Comment by AndInTheClouds** [comment]
fixed in version 2.3.2
