### ISSUE TITLE
Set List Lacks Song Titles

### ISSUE THREAD

**Issue by NorfolkGreg** [AndInTheClouds/chordreader2#58]
Just downloaded v2.3.2 over v2.2.0
I find that Set Lists have no song titles. That makes it rather tricky to manage the order of items.

(Running on Moto G62 5G phone (Android 13) as a test before attempting to install it on my, elderly,  tablet.

**Comment by NorfolkGreg** [comment]
Same with my Tablet, Samsung SM-T580 (Android 8).

**Comment by AndInTheClouds** [comment]
fixed in version 2.4.0

**Comment by NorfolkGreg** [comment]
Hope 2.4.0 makes it's way to F-Droid soon.

**Comment by AndInTheClouds** [comment]
Just dropped my friend. Have fun.

Am 18. Dezember 2024 22:51:02 MEZ schrieb NorfolkGreg ***@***.***>:
