### ISSUE TITLE
Spaces in file names are not supported

### ISSUE THREAD

**Issue by dynobo** [AndInTheClouds/chordreader2#6]
First: Thanks for reviving this app, good chord readers are in short supply within the FOSS ecosystem. :nerd_face: :guitar: 

Now to the issue:

I synced the contents of the `/chord reader 2/` folder with my personal, already existing chords/lyrics folder (through nextcloud). ChordReader2 shows my own files correctly in the Songs-overview, but won't open them: Clicking on a file just does nothing (no error, doesn't open).

I tried a bit around and noticed that when saving a chord from the internet within ChordReader2, it replaces space (` `) in the filename with underscores (`_`). I tried doing the same manually for some of my already existing chord files (e.g. `greenday - longview.txt` -> `greenday_-_longview.txt`), é voilà: They now open correctly.

So, it seems to me like ChordReader2 has an issue with spaces in file names. While replacing them manually seems to be a valid workaround, I still would prefer if ChordReader2 could handle them.

What do you think? Would that be a lot of effort?

**Comment by AndInTheClouds** [comment]
I fixed that. Whitespaces in filenames are supported now. ;)
