### ISSUE TITLE
[Feature request] Option to specify custom folder for storing chords

### ISSUE THREAD

**Issue by dynobo** [AndInTheClouds/chordreader2#7]
Currently, ChordReader2 stores all chords in `./chord_reader_2/` folder. 

It would be useful to make this configurable to _any_ custom folder: That would help me to keep my files organized in general, but especially would ease integration with already configured synchronization services.

Thanks!

**Comment by deddc23efb** [comment]
Came here to bump this feature request.  A common use case to consider would be someone bulk copying crd files to a tablet either over the network or on an SD card.  would be great to be able to point chordreader2 at the folder and have it suck in the files (or simply use the files in place.)

**Comment by AndInTheClouds** [comment]
So, here we are. Took me some time, but I hope it works now. Its related to the storage access framework of android now applicable for versions as of Android 8.1. Thus, you'll get permission request and folder picker for your custom folder. 

Release 2.1.2 should be available within the next days after the next fdroid build cycle.
