### ISSUE TITLE
font size

### ISSUE THREAD

**Issue by wolfhoog** [AndInTheClouds/chordreader2#8]
I liked this app because I could change the font size so I could read lyrics on the small smartphone display without glasses.
Why did you delete this function in the new version?
Do you know any alternative which still can do this?

**Comment by AndInTheClouds** [comment]
Sorry not to provide an appropriate information. I changed the text size adaption to two-finger-zoom in the song view. So there is no need for fixed settings anymore.

**Comment by wolfhoog** [comment]
Yes, sorry for opening two issues which actually turned out to be one. The app also closed with two finger-zoom. But reinstall helped.
Thanks very much for this great app!
