### ISSUE TITLE
app closes

### ISSUE THREAD

**Issue by wolfhoog** [AndInTheClouds/chordreader2#9]
And since the new version the app suddenly closes again and again every time I touched the screen to often.
I liked to pause scrolling by touching the text. This seems to make problems. Or maybe when I restart the scrolling by moving my thumb. Or both.
This is really a problem when I have to reopen the app and then the file on stage again and again.
And it was for sure no problem with the old version.

**Comment by AndInTheClouds** [comment]
I guess, there may be a problem with the app's internal database, as I changed something there. Could you re-install the app to verify? Your songs and the app folder should be untouched, though. However, backup is always advisable.

**Comment by wolfhoog** [comment]
Sorry for not answering earlier. The backup needed time, thought really wasn't necessary. Yes, deinstalling and reinstalling it helped. Thanks very much for this great app!
